### ISSUE TITLE
I wanna communicate some thing about RL in energy dispatch problem

### ISSUE THREAD

**Issue by stvsd1314** [EnergyQuantResearch/Optimal-Energy-System-Scheduling-Combining-Mixed-Integer-Programming-and-Deep-Reinforcement-Learning#1]
Hello, thanks for your excellent work. I benefit a lot from it. I have some question about DRL as below:
Do you try to solve the hybrid action space reinforcement problem? such as unit comittment and dispatch problem.
Once i see you repo's title, i guess your work is about the problem that i told. So i am eager to  exchange study with you.
Here is my wechat id: 15736716954 .

**Comment by EnergyQuantResearch** [comment]
Hey Just get back from the holiday. I see several papers doing hybrid action space problems in unit commitment. We can discuss this later.
